import {
  Brain,
  TrendingUp,
  Trophy,
  Newspaper,
  Globe,
  Zap,
  Cpu,
  Microscope,
  Rocket,
  Heart,
  Music,
  Film,
  BookOpen,
  GraduationCap,
  Landmark,
  ShieldCheck,
  Leaf,
  Utensils,
  Plane,
  Car,
  Gamepad2,
  Palette,
  Camera,
  Code,
  Database,
  Bitcoin,
  DollarSign,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  brain: Brain,
  "trending-up": TrendingUp,
  trophy: Trophy,
  newspaper: Newspaper,
  globe: Globe,
  zap: Zap,
  cpu: Cpu,
  microscope: Microscope,
  rocket: Rocket,
  heart: Heart,
  music: Music,
  film: Film,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  landmark: Landmark,
  "shield-check": ShieldCheck,
  leaf: Leaf,
  utensils: Utensils,
  plane: Plane,
  car: Car,
  gamepad2: Gamepad2,
  palette: Palette,
  camera: Camera,
  code: Code,
  database: Database,
  bitcoin: Bitcoin,
  "dollar-sign": DollarSign,
  "bar-chart-3": BarChart3,
};

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Newspaper;
}

export const availableIcons = Object.keys(ICON_MAP);
